version: "3.5"

services:
  coredns:
    build: .
    depends_on:
      - mysql
    ports:
      - "53:53/udp"
    environment:
      DOMAIN: ${DOMAIN}
      APIKEY: ${APIKEY}
      NAMESERVER_IP: ${NAMESERVER_IP}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mysql:
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    restart: always
